### ISSUE TITLE
Add details to add an SSH key

### ISSUE THREAD

**Issue by garethtdavies** [balena-io/balena-cli-masterclass#16]
If using `balena ssh` with the balena VPN you must have an SSH key added to your account otherwise:

```
gh_garethtdavies@ssh.balena-devices.com: Permission denied (publickey).
```

If using locally there is no requirement for the SSH key. Issue here: https://github.com/balena-io/docs/issues/1238

**Comment by vipulgupta2048** [comment]
+1 face the same issue. @kaisoz I can make a quick PR if you like. 
Happy to help!

**Comment by xginn8** [comment]
@vipulgupta2048 PRs always welcome :)
