### ISSUE TITLE
Cross-platform build on Apple M1 Silicon

### ISSUE THREAD

**Issue by snowake4me** [balena-io/balena-cli-masterclass#41]
Team Balena-

Revisiting the CLI masterclass and refreshing some memories as I get my new Mac Studio all setup for Balena development work.

I get to step 5.1 where I'm executing the following command:

`% balena build --fleet cliFleet --emulated`

And it just seems to hang indefinitely while building main - on step 5/7.

For comparison, I exercised the same command on my Intel-based MBP -- and the build completed successfully in fairly short order.

Balena CLI version:  14.5.15
MacOS: 13.0 (Ventura) (on my Intel-based MBP and Apple M1 Max Mac Studio)

Any #ProTips for compiling on Apple Silicon?  Not only is this Mac Studio fairly beefy (M1 Max, 64GB RAM) - but  given that the M1 is also ARM-based, I might have guessed the 'emulation overhead' to be even less than when invoked on an x64 CPU.

I know there are mechanisms for running CLI commands under rosetta 2 - but the Balena CLI _seems_ to be working, otherwise, without any such shenanigans.

Thoughts / Guidance / RTFM links all welcome and appreciated.

**Comment by snowake4me** [comment]
Here's what my output looks like:

`% balena build --fleet cliFleet --emulated
[Info]    No "docker-compose.yml" file found at "/Users/billy/code/balena/balena-cli-masterclass"
[Info]    Creating default composition with source: "/Users/billy/code/balena/balena-cli-masterclass"
[Build]   Building services...
[Build]   main Preparing...
[Info]    Building for aarch64/raspberrypi4-64
[Info]    Emulation is enabled
[Build]   main Step 1/7 : FROM balenalib/raspberrypi4-64-node:8
[Build]   main  ---> a3865ad22f08
[Build]   main Step 2/7 : COPY [".balena/qemu-execve","/tmp/qemu-execve"]
[Build]   main  ---> Using cache
[Build]   main  ---> 4d1fca1caf73
[Build]   main Step 3/7 : WORKDIR /usr/src/app
[Build]   main  ---> Using cache
[Build]   main  ---> d786ca724cfa
[Build]   main Step 4/7 : COPY ["package.json","package-lock.json","./"]
[Build]   main  ---> Using cache
[Build]   main  ---> b9dc4340285c
[Build]   main Step 5/7 : RUN ["/tmp/qemu-execve","-execve","/bin/sh","-c","npm install --ci --production     && npm cache clean --force     && rm -rf /tmp/*"]
[Build]   main  ---> [Warning] The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
[Build]   main  ---> Running in 27daa0d80b4c
[Build]   main Here are a few details about this Docker image (For more information please visit https://www.balena.io/docs/reference/base-images/base-images/):
[Build]   main Architecture: ARM v8
[Build]   main OS: Debian Buster
[Build]   main Variant: run variant
[Build]   main Default variable(s): UDEV=off
[Build]   main The following software stack is preinstalled:
[Build]   main Node.js v8.17.0, Yarn v1.22.4
[Build]   main Extra features:
[Build]   main - Easy way to install packages with `install_packages <package-name>` command
[Build]   main - Run anywhere with cross-build feature  (for ARM only)
`

**Comment by vipulgupta2048** [comment]
Thanks for mentioning this. I will reach out to a few folks running Apple silicon and see if they can reproduce this problem.  I would additionally recommend posting about this on balena Forums to get more eyes on this and see if folks have found a workaround for this.

**Comment by snowake4me** [comment]
@vipulgupta2048  Thanks for the pointer to the forums: Sure enough, my post there got a quick response:

"Have you tried it without the --emulated flag?"

Works great!

**Comment by vipulgupta2048** [comment]
Awesome! Glad to help
