### ISSUE TITLE
"Local Mode" is activated in "Settings", not in "Actions"

### ISSUE THREAD

**Issue by tmh-grunwald-markus** [balena-io/balena-cli-masterclass#42]
The documentation tells me to activate "Local Mode" in the Actions:

https://github.com/balena-io/balena-cli-masterclass/blob/d8214a69984e9ff1df3f63b5cace5b3ac58040a6/README.md?plain=1#L503-L505

Instead, it is activated in the "Settings" tab.

**Comment by floion** [comment]
Indeed @tmh-grunwald-markus thanks for spotting it. It's been changed now and it's even called just `Local mode` nowadays. Would you mind creating a PR to fix it?

**Comment by tmh-grunwald-markus** [comment]
@floion done.
